joint_limits:
  arm:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
  spine:
    has_velocity_limits: true
    max_velocity: 0.02
    has_acceleration_limits: true
    max_acceleration: 1.0
