sensors:
 - sensor_type: point_cloud_sensor
   point_cloud_topic: /camera/depth_registered/points
   max_range: 15.0
   frame_subsample: 1
   point_subsample: 1
   self_mask:
       min_sensor_dist: .1
       self_see_default_padding: .01
       self_see_default_scale: 1.0
       self_see_links:
         - name: arm
           padding: .1
